"""Stable import surface for property catalogs and runtime helpers."""

from __future__ import annotations

from .property_catalog import PAGE_PROPERTIES, REPORT_PROPERTIES, VISUAL_PROPERTIES, PropertyDef
from .property_runtime import (
    _coerce_simple,
    _decode_literal,
    _derive_group,
    _find_entry,
    _get_by_path,
    _get_container_prop,
    _get_dynamic_chart_prop,
    _infer_value_type,
    _match_chart_selector,
    _object_property_reverse_map,
    _parse_chart_prefix,
    _property_alias_map,
    _resolve_value_type,
    _schema_chart_properties,
    _schema_validate_chart_prop,
    _set_by_path,
    _set_container_prop,
    _set_dynamic_chart_prop,
    _try_auto_resolve_chart_property,
    canonical_object_property_name,
    chart_property_hint,
    decode_pbi_value,
    encode_pbi_value,
    get_known_default,
    get_property,
    get_visual_objects,
    list_properties,
    normalize_property_name,
    property_aliases_for,
    set_property,
    suggest_property_names,
)

__all__ = [
    "PAGE_PROPERTIES",
    "REPORT_PROPERTIES",
    "VISUAL_PROPERTIES",
    "PropertyDef",
    "_coerce_simple",
    "_decode_literal",
    "_derive_group",
    "_find_entry",
    "_get_by_path",
    "_get_container_prop",
    "_get_dynamic_chart_prop",
    "_infer_value_type",
    "_match_chart_selector",
    "_object_property_reverse_map",
    "_parse_chart_prefix",
    "_property_alias_map",
    "_resolve_value_type",
    "_schema_chart_properties",
    "_schema_validate_chart_prop",
    "_set_by_path",
    "_set_container_prop",
    "_set_dynamic_chart_prop",
    "_try_auto_resolve_chart_property",
    "canonical_object_property_name",
    "chart_property_hint",
    "decode_pbi_value",
    "encode_pbi_value",
    "get_known_default",
    "get_property",
    "get_visual_objects",
    "list_properties",
    "normalize_property_name",
    "property_aliases_for",
    "set_property",
    "suggest_property_names",
]
