table Customers
	lineageTag: f088de9b-509b-4fb0-be6d-10a8fdb18492

	column CustomerID
		dataType: string
		lineageTag: 079c7b4e-050d-4d89-b0b5-0e3e35f3ec21
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 6208b011-80a4-4c3c-9b0b-8c44bbd98ad4
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 093f6244-c32d-45da-8395-b6434bccf8d7
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: eeae6984-feb8-4852-ad03-ec5e09cacc27
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\WSL\pbi-report-builder\fixtures\sample-data\Customers.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", type text}, {"CustomerName", type text}, {"Region", type text}, {"Segment", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

