table Date
	lineageTag: 9280790a-1a43-4b63-9216-2c2c10bcf134

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2ef98ce0-b29f-402f-a954-91373ca91d92
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 1219c513-7cdb-4ec7-ba91-ecd7d995cfd0
			defaultHierarchy: LocalDateTable_6809f789-ca23-4187-a37b-4db3392ec26d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 28d19e7e-85a2-4e25-a47c-043016dae986
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column MonthNumber
		dataType: int64
		formatString: 0
		lineageTag: 01e6aebe-439a-4e3d-a889-2966438c5e93
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 452393eb-77ae-46e3-a1b6-51087deff7af
		summarizeBy: none
		sourceColumn: MonthName

		annotation SummarizationSetBy = Automatic

	column DayOfMonth
		dataType: int64
		formatString: 0
		lineageTag: febf3ca6-2c72-49b1-94c7-0defa3973674
		summarizeBy: sum
		sourceColumn: DayOfMonth

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: e7d62cb3-b81c-4a45-8377-1bff4fb72a3b
		summarizeBy: none
		sourceColumn: DayName

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: ff0f5a5d-7ea5-48dd-ab58-15f6f3824c52
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e4326d4f-5162-42ab-9edf-b1fa631a60a3
		summarizeBy: none
		sourceColumn: IsWeekend

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\WSL\pbi-report-builder\fixtures\sample-data\Date.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Year", Int64.Type}, {"MonthNumber", Int64.Type}, {"MonthName", type text}, {"DayOfMonth", Int64.Type}, {"DayName", type text}, {"Quarter", type text}, {"IsWeekend", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

