table Promotion
	lineageTag: 85b3cc9c-1b72-448e-9a6e-f973c2752f42

	column PromotionKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ac6945c0-4306-4c50-b68e-a332376fc96d
		summarizeBy: none
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column PromotionName
		dataType: string
		lineageTag: 1fc4e361-ff0d-4c40-9a62-6bb29cd6bdb1
		summarizeBy: none
		sourceColumn: PromotionName

		annotation SummarizationSetBy = Automatic

	column PromotionType
		dataType: string
		lineageTag: 6b719f17-fa5f-416e-b92c-82e81bf1dcc1
		summarizeBy: none
		sourceColumn: PromotionType

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e129c8c5-2467-4b2c-96b2-9795788c3269
		summarizeBy: none
		sourceColumn: StartDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8c8b9ac4-7b13-496a-953b-1629ff4cdc14
		summarizeBy: none
		sourceColumn: EndDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Promotion = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\WSL\pbi-report-builder\fixtures\real-report-fixtures\report-01-kitchen-sink\data\Promotion.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"PromotionKey", Int64.Type}, {"PromotionName", type text}, {"PromotionType", type text}, {"StartDate", type date}, {"EndDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

