table Sales
	lineageTag: 585d50a0-3e74-46c9-9aeb-73444952b93e

	column SalesKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f63ab996-222a-47f2-911a-4ef315094827
		summarizeBy: count
		sourceColumn: SalesKey

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: f98c7f15-650d-4016-a2cc-ebd80ab1f8ba
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ShipDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3e5546f-59df-4f2b-a9d4-ada049eb2c07
		summarizeBy: none
		sourceColumn: ShipDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 582e1483-7add-4007-86c3-58a27a4aca6b
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8d248500-e4d4-4dec-896f-8a2b728d4178
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5fd9d848-2288-446c-a86b-1aba65996478
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column ChannelKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c8ea3290-7ec7-4034-82e7-5af1e9ef4a70
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5b3ba108-a4df-44ca-a587-3b38c36aa2ca
		summarizeBy: none
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column OrderNumber
		dataType: string
		lineageTag: 9d854568-0102-47cd-b07c-5138ad41367b
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 91285673-99fa-469a-b9dc-c1679e6db655
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		lineageTag: 6aa4959d-781c-443b-998f-6a94ed1892e6
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitCost
		dataType: double
		lineageTag: ada342e1-f65f-4019-910c-ef335f2183a6
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: 981cc2e5-5734-4139-a55f-4d6df82fceaa
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesAmount
		dataType: double
		lineageTag: 14d1e501-ae8c-4e82-ada2-a3a934bf08ac
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MarginAmount
		dataType: double
		lineageTag: 3bee8cf7-de29-42ad-a6b8-617850d8fcc2
		summarizeBy: sum
		sourceColumn: MarginAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReturnedFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c08e0f6e-bc14-4b3d-961f-6478d3c0d448
		summarizeBy: none
		sourceColumn: ReturnedFlag

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\WSL\pbi-report-builder\fixtures\real-report-fixtures\report-01-kitchen-sink\data\Sales.csv"),[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SalesKey", Int64.Type}, {"OrderDate", type date}, {"ShipDate", type date}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"StoreKey", Int64.Type}, {"ChannelKey", Int64.Type}, {"PromotionKey", Int64.Type}, {"OrderNumber", type text}, {"Quantity", Int64.Type}, {"UnitPrice", type number}, {"UnitCost", type number}, {"DiscountAmount", type number}, {"SalesAmount", type number}, {"MarginAmount", type number}, {"ReturnedFlag", type logical}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

