table Store
	lineageTag: be74baa8-b3d3-4d3f-b3ed-baecaddefb22

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3f45b0ca-a257-424d-8e09-2befc6a0bce4
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

	column StoreName
		dataType: string
		lineageTag: 30973fff-d9e6-450c-b208-513e01150879
		summarizeBy: none
		sourceColumn: StoreName

		annotation SummarizationSetBy = Automatic

	column StoreType
		dataType: string
		lineageTag: aeab6e97-ce5b-43c7-93de-9f73313859fd
		summarizeBy: none
		sourceColumn: StoreType

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: eadedc97-c7ba-4cf4-af29-d4393ad18033
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: eba88f27-554a-4194-9b44-b62c8cfb8352
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: a5624ccd-33c0-4e19-8139-7adcb3cf8b7d
		summarizeBy: none
		sourceColumn: OpenDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Store = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\WSL\pbi-report-builder\fixtures\real-report-fixtures\report-01-kitchen-sink\data\Store.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StoreKey", Int64.Type}, {"StoreName", type text}, {"StoreType", type text}, {"Region", type text}, {"Manager", type text}, {"OpenDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

